astraw/stdeb

README.rst, stdeb/command/common.py, stdeb/util.py
Based on discussion ros/rosdistro#5944
Currently the Python 3 Debian package always has a dependency on the Python 3 version of the system where the packaging is run.
This patch adds support for putting `X-Python3-Version` in the `stdeb.cfg` file. If the new option is present and gets passed into the source block of the Debian control file. Additionally `${python3:Depends}` will be omitted to avoid also adding the explicit dependency on the Python version of the system running the packaging command.
If the new option is not in the `stdeb.cfg` file the behavior is unchanged.
=> add --x-python3-version and --force-x-python3-version options

stdeb/util.py
In Python 3, the result from Popen is bytes by default, but stdout expects a str, so pass universal_newlines=True to Popen.
=> Fix applying patch files under Python 3

stdeb/util.py
dh_desktop no longer does anything for quite a while - lintian warning since 2009
https://lintian.debian.org/tags/dh_desktop-is-deprecated.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=531164
=> remove deprecated dh_desktop call

README.rst, stdeb/util.py
This pull request adds a new optional configuration field to stdeb.cfg: `Suite3`.
The Suite3 field contains an alternative distname value which is used when building with python3 only.
If the field is not present, python3 builds will use the Suite value or its default.
If a Suite3 field is present, running stdeb with both python2 and python3 will raise a ValueError since only one distname can be used.
The ROS team is hoping to use this feature to avoid releasing python2 variants of our packages onto newer Ubuntu versions where Python 2 support is not planned. It has been tested locally using this example config https://github.com/nuclearsandwich/bloom/blob/example-suite3/stdeb.cfg
=> Add support for Suite3 option to release into different suites based on python version.

stdeb/cli_runner.py
In python3, the built-in map() function is returning an iterator, not a
list.
As a result, we can use the keyword "in" multiple times.
I propose to cast the result of map() into a list to fix the issue.
Signed-off-by: Arnaud Morin <arnaud.morin@corp.ovh.com>
=> Fix map() iterator issue in python3

stdeb/util.py
This patch handles correctly filenames with spaces in zip archive.
=> Handle path with spaces in zip tarball

stdeb/util.py
**OS X:**
```
date -R
date: illegal option -- R
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
[-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```
**On Linux:**
```
date -R
Mon, 26 Oct 2015 12:28:45 +0000
```
```
python -c 'import time; print time.strftime("%a, %e %b %Y %H:%M:%S %z")'
Mon, 26 Oct 2015 12:38:23 +0000
```
=> get_date_822 pythonic way. OS X does not have -R option for *date*

README.rst, stdeb/util.py
On Ubuntu Focal the Python 2 Debian package name is `python2`. So when generating Python 2 Debian package on Focal the `${python:Depends}` expands to something like `python2 (<< 2.8), python2 (>= 2.7)`.
With the new configuration option `Python2-Depends-Name` it can be configured to `python` which overrides the Debian package in `python:Depends`. The opposite (releasing on e.g. Ubuntu Bionic and configuring the override to `python2`) should also be feasible.
=> add configuration file option Python2-Depends-Name

README.rst, stdeb/command/common.py, stdeb/util.py
This new option allow the builing of the package using dh_virtualenv.
This is very useful when you want to build a package that embed its
own dependencies and dont touch the system at all.
This is mainly designed to be used for python applications.
Signed-off-by: Arnaud Morin <arnaud.morin@corp.ovh.com>
=> Add an option --with-dh-virtualenv

README.rst, stdeb/command/bdist_deb.py, stdeb/command/common.py, stdeb/command/sdist_dsc.py, stdeb/util.py
This add a new option ignore-source-changes which is false by default.
This option can be used to force building a package even if there is
some changes in the source code.
It basically add -i.* to dpkg-buildpackage, which is then given to
dpkg-source.
Signed-off-by: Arnaud Morin <arnaud.morin@corp.ovh.com>
=> Add an option named ignore-source-changes

stdeb/util.py
The "changes" can look scary. I formatted the full script to be pip compliant.
This fix the 
On Ubuntu 20.04 I needed to install dh-python package too.
Fixes #140 and #153.
=> fix checking for python3-all (instead of python-all) when using only Python 3

README.rst, stdeb/util.py
See https://reproducible-builds.org/docs/source-date-epoch/
By default the timestamp in the generated changelog is *now* which results in a non-reproducible build since every invocation generates a different `.deb`. With this patch the caller can set the environment variable `SOURCE_DATE_EPOCH` to e.g. the timestamp of the tagged commit to ensure that the produced `.deb` is reproducible (byte-wise identical).
=> use SOURCE_DATE_EPOCH if set for timestamp in generated changelog

stdeb/command/common.py, stdeb/util.py
This avoid deprecation warnings on current platforms and should be compatible with all platforms still being supported.
=> update debhelper compat version from 7 to 9

README.rst, stdeb/command/common.py, stdeb/util.py
feat: added flag --with-dh-systemd to pass on the flag to rules so units can get enabled at install time when compat level is <7 as hardcoded right now
=> feat: added flag --with-dh-systemd

stdeb/command/common.py, stdeb/util.py
This is a rebase of #103 and the "Homepage: ..." is being added to the `source_stanza_extras` variable instead of adding another placeholder to the template.
=> use setuptools "url" field for "Homepage" field in debian/control

stdeb/util.py
Specifies the python version to use for `dh_virtualenv` (As indicated with the [`dh_virtualenv` documentation](https://dh-virtualenv.readthedocs.io/en/latest/howtos.html#building-packages-for-python3))
=> dh_virtualenv: specify python version 

README.rst
There are two issues that this PR fixes:
- The URL that is retrieved using wget doesn't exist. These URLs were placed in the README 13 years ago, so I think it's likely that PyPI has changed the structure at some point.
- Although it is not literally stated in the README, I take it that `pypi-download` should be used to download source files from PyPI, instead of wgetting them. According to the changelog, `pypi-download` was added in version 0.7.1 (2014), so I think it's likely that updating the README was simply forgotten when this tool was introduced.
=> README: Replace wget calls with pypi-download

README.rst, stdeb/command/common.py, stdeb/command/sdist_dsc.py, stdeb/util.py
Allows user to specify a specific GPG key with `--sign-key KEYNAME` instead of always using the default key.
=> allow specifying signing key

stdeb/util.py
The udev rule filename must match the package name for dh_installudev to
recognize it.
=> Fix udev rule filename(s)

stdeb/downloader.py, stdeb/pypi_simple.py
This was introduced in 0787a84 which shows you what comes of adding last minute unreviewed changes without having CI up.
This is a fixup after #201 which I will merge directly.
=> Fix cyclic import dependency by moving USER_AGENT to pypi_simple client.

stdeb/util.py, test2and3.sh
Ubuntu Focal and Jammy install a `python2` binary with python-all-dev.
Rather than requiring that tests and downstream packages always install python-is-python2 (seemingly unavailable on jammy), check the current path for each binary and use the first one found, preferring `python` when it is available to maintain current behavior but using `python2` if it's the only option.
This unblocks testing python2 package generation with python3-stdeb in test-2and3.sh.
However, this case doesn't appear to be tested so I've added an additional case when testing python3.
Although I am planning to drop support for installing/running stdeb from python2 (#198) I am hoping to preserve, at least for a while, support for generating python2 packages using the python3 version of stdeb.
=> Use an available python2 binary name in debian templates.

stdeb/cli_runner.py, stdeb/util.py
`SafeConfigParser` has been deprecated since Python 3.2. There has been a shim which has been finally removed in Python 3.11 [in this commit](https://github.com/python/cpython/commit/1fc41ae8709e20d741bd86c2345173688a5e84b0) in favor of simply `ConfigParser`.
This means that this utility won't work if users are on Python >= 3.11 (which is the case for Ubuntu Noble).
In this PR I migrated to `ConfigParser` and took the liberty to remove the `try except` that made the package work for Python 2 since Python 2 is been EOL for more than 4 years now (this fix would have been more boilerplate otherwise).
`readfp` was also deprecated in favor of `read_file`.
Try building a package on Ubuntu 22.04, then try on Ubuntu 24.04. For example, when
trying to build …
=> Migrate off SafeConfigParser

stdeb/util.py, stdeb/which.py
This regression was introduced in
https://github.com/astraw/stdeb/pull/203 and incorporated into the 0.10.1 release (which was not ever tagged and published).
=> Fix regression in 0.10.1 by adding a shim function.
